##############################################
## These are required for the server to run ##
##############################################

# The host or domain this server is running on. 
host = '127.0.0.1'

# Port to use when listening for incomming connections
port = 8080

# Location of the document root, where the resources of the 
# server are stored. Most linux machines this is /var/www/html/
# Depending on where you set this, make sure you have set the
# premissions correctly.
doc_root = 'http'

# Types of images the server will serve. If the image is not
# on this list, then the server will ignore it.
# (not implemented)
image_list = ['ico', 'jpeg', 'jpg', 'gif', 'png']

# Types of files the server will serve. If a file extension
# is not on this list, the server will ignore it.
# (not implemented)
file_list = ['html', 'htm', 'css', 'js', 'txt']

###################################################
## These are not required, but should be reviwed ##
###################################################

# Set the maximum buffer TinyHTTP uses (not enforced)
max_buffer = 2048

# If the root file is not specified then `index.html` is assumed.
# Not setting this and not haveing an `index.html` would make any
# root request return 404 Not Found.
root_file = 'index.html'

# The default root file. If `root_file` is not specified this is
# the fallback. If nothing is specified here, then `index.html`
# is the assumption.
#default_root_file = 'index.html'

# If a client requests a resource that can not be found, this is
# the page returned.
#custom_404 = 'my_custom_404.html'

#######################################
## Print debug information to stdout ##
#######################################
#
# Print all header information received from a client to stdout
print_header_information = true
